# Generated by Django 5.0 on 2023-12-29 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_country_alter_ordershippingaddress_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordershippingaddress',
            name='category_address',
            field=models.CharField(help_text='category name', max_length=255, null=True),
        ),
    ]
