# Generated by Django 5.0 on 2023-12-29 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_ordershippingaddress_category_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordershippingaddress',
            name='category_address',
        ),
    ]
