# Generated by Django 5.0 on 2023-12-29 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_remove_ordershippingaddress_category_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordershippingaddress',
            name='category_address',
            field=models.CharField(help_text='category name', max_length=255, null=True),
        ),
    ]
