# Generated by Django 5.0 on 2023-12-30 11:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_alter_orderline_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordershippingaddress',
            name='order',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.order'),
        ),
    ]
