# Generated by Django 5.0 on 2024-01-26 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_alter_orderline_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderline',
            name='completed',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
