# Generated by Django 5.0 on 2024-01-26 12:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_orderline_completed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderline',
            name='product_name',
        ),
        migrations.AddField(
            model_name='orderline',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.product'),
        ),
    ]
