# Generated by Django 5.0 on 2024-01-26 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_remove_orderline_product_name_orderline_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderline',
            name='line_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
