# Generated by Django 5.0 on 2024-01-26 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_alter_order_total_alter_orderline_line_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='total',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Order total'),
        ),
        migrations.AlterField(
            model_name='orderline',
            name='line_price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
