# Generated by Django 5.0 on 2024-01-27 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_alter_order_total_alter_orderline_line_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderline',
            name='completed',
        ),
    ]
