# Generated by Django 5.0 on 2024-02-03 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0018_orderline_default_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sku',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='upc',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
