# Generated by Django 5.0 on 2024-02-03 09:37

from django.db import migrations
from django.db.models import F


def migrate_sku_and_upc(apps, schema_editor):
    Product = apps.get_model('shop', 'Product')
    Product.objects.all().update(upc=F("id"), sku=F("id"))  # hit DB only 1 time


class Migration(migrations.Migration):
    dependencies = [
        ('shop', '0019_product_sku_product_upc'),
    ]

    operations = [
        migrations.RunPython(migrate_sku_and_upc)
    ]
